### ISSUE TITLE
Adding Scala Graph 

### ISSUE THREAD

**Issue by max-leuthaeuser** [danielkroeni/trails#1]
I forked this project and updated to Scala 2.11.5 quite easily.
But I was not able to adapt Scala Graph as alternative for the provided Neo4j and Blueprints subprojects due typing problems (e.g. no common abstraction for node and edge).

How could one integrate Scala Graph?
(http://www.scala-graph.org/)

**Comment by danielkroeni** [comment]
Hi Max,

Sorry for answering late and congratulations for issue #1 ;)

I just cloned your updated version, added a new Scala Graph subproject and faced the same questions / problems as you did. It's not too hard to choose Any as the common super type for Edge and Node. But how would you extract property values from Any? 
It seems that trails really is a traversal API for "property graphs" where nodes and edges have associated  key-value pairs, a unique id and where edges are named.
The model of Scala Graph is much more flexible. Nodes could be of any type! 

Now i could imagine a typeclass based trails-like API which offers functionality only if can be supported by the type of the node / edge.

The signature of the method get could be something like this:

```
trait KeyValueAccess[E] {
  def get[A](elem: E, name: String): A
}

def get[A](name: String)(implicit kva: KeyValueAccess[E]): A
```

For any E for which a KeyValueAccess instance is provided we could offer property access.

trails doesn't currently generalize well to arbitrary graph apis but I think we could provide as much functionality as is supported by the types which are used as nodes and edges.

**Comment by max-leuthaeuser** [comment]
One could implement the property access via the Dynamic Trait.
(http://www.scala-lang.org/api/current/#scala.Dynamic)

I have done something very similar in another project and its quite convenient (and typesafe if done with generics).

**Comment by danielkroeni** [comment]
I'm not sure what you would gain by using Dynamic. The result would not be more safe than the current approach using `get`. Or do you think about using macros to test whether a selected property exists?

Currently `get` is used within `map` to project a value from the current element.
`val petNames = friends ~> out("pet") ^^ get[String]("name")` where ``^^` is a synonym for map. 
What you can do is just accessing the properties of your node / edge which is safe in a true sense: `val petNames = friends ~> out("pet") ^^ _.name`. 

Or would you propose something like this? `val petNames = friends ~> out("pet").name[String]` where name is dynamically resolved on the node?

Maybe we can just throw out `get` and `Elem` and leave it to the specific implementation how it handles property access. In the case of Scala Graph no additional functionality would be needed. For property graph APIs we could just implement `get` as it currently is.

Another assumption which is baked into trails is that each node and each edge can be uniquely identified using an `Id`. This needs to be relaxed as well (maybe by parametrizing trails with a function to compare nodes and edges for identity).

At the moment I will not find any time playing around with trails by myself. But if you are interested in implementing some ideas im happy to discuss ideas and to take pull requests.
